version: '3.9'

services:
  web:
    build: .
    container_name: go-auth-service
    env_file:
      - .env
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/src/app
    command: air ./cmd/main.go -b
    depends_on:
      - mysql
      - redis

  redis:
    image: redis:7.0.15-alpine3.20
    container_name: go-auth-redis
    volumes:
      - ./docker/data/redis:/data
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: go-auth-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASS}"
      MYSQL_DATABASE: "${DB_NAME}"
    volumes:
      - ./docker/data/db:/var/lib/mysql
    ports:
      - "3305:3306"

volumes:
  mysql-db: